/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import connectionModel.EntertainerConnection;
import connectionModel.EventConnection;

import dataModel.Customer;
import dataModel.Entertainer;
import dataModel.Event;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ste
 */
public class EngagementFrame extends javax.swing.JFrame {
 int cusNum;
    Calendar cal;
    Calendar cal2;
    Calendar caly;
    Calendar caly2;
    Calendar ca;
    Calendar ca2;
    Calendar c;
    Calendar c2;
    Date date;

    /**
     * Creates new form EngagementFrame
     */
    public EngagementFrame() {
        initComponents();

        EventConnection initConEv = new EventConnection("coursework");
        initConEv.getEventNames(jComboBox5);
        initConEv.getEventNames(selectEventNameCombo);
        initConEv.showCustomerEmails(CustomerEmailCombo);
        initConEv.showCustomerNamesToCombo(RemoveCustomerCombo);
       initConEv.showCustomerNames(CusNameTable);
       initConEv.showCustomerWithAddresses(CusNameAddTable);
       initConEv.getEventTypes(jComboBox6);
        initConEv.closeConnection();

        EntertainerConnection InitConEc = new EntertainerConnection("coursework");
        InitConEc.getAllnames(chooseEntNameCombo);
        InitConEc.getAllnames(RemoveEntertainerCombo);
        InitConEc.getAllnames(jComboBox7);
        InitConEc.getAllnames(SelectEntNameCombo);
        InitConEc.showEntertainersNames(EntNameTable);
        InitConEc.closeConnection();
     

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        Pane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        f = new javax.swing.JTextField();
        l = new javax.swing.JTextField();
        s = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        p = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        addNewCustomerButton = new javax.swing.JButton();
        addNewEntertainerButton = new javax.swing.JButton();
        entertainerFeeField = new javax.swing.JTextField();
        entertainerTypeField = new javax.swing.JTextField();
        entertainerNameField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        EntNameTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        CusNameTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        RemoveEntertainerCombo = new javax.swing.JComboBox<>();
        RemoveCustomerCombo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        OverallEntPopularityButton = new javax.swing.JButton();
        TotalEntCountButton = new javax.swing.JButton();
        EntCountByDateButton = new javax.swing.JButton();
        jComboBox7 = new javax.swing.JComboBox<>();
        EvtCountTotalButon = new javax.swing.JButton();
        ShowAllCustomers = new javax.swing.JButton();
        showAllEventButton = new javax.swing.JButton();
        evtCountByDateButton = new javax.swing.JButton();
        evtPopularity = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        EntMostPopularButton = new javax.swing.JButton();
        CustomersByLoyalty = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        FinanceDateTo = new datechooser.beans.DateChooserPanel();
        FinanceDateFrom = new datechooser.beans.DateChooserPanel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        CustomerInvoiceButton = new javax.swing.JButton();
        ShowFinancesForPerion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fNameField = new javax.swing.JTextField();
        lNameField = new javax.swing.JTextField();
        addField = new javax.swing.JTextField();
        pCodeField = new javax.swing.JTextField();
        chooseEntNameCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        eMailField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        dateChooserPanel1 = new datechooser.beans.DateChooserPanel();
        eventNameField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        CreateFromNew = new javax.swing.JButton();
        cityField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        evTypeField = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        selectEventNameCombo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        SelectEntNameCombo = new javax.swing.JComboBox<>();
        AddEntToEventButton = new javax.swing.JButton();
        CreateFromExisting = new javax.swing.JButton();
        CustomerEmailCombo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        CusNameAddTable = new javax.swing.JTable();

        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pane.setBackground(new java.awt.Color(204, 255, 255));

        jLabel8.setText("Customer");

        jLabel28.setText("Email");

        jLabel27.setText("Postcode");

        jLabel12.setText("City");

        jLabel11.setText("House Number");

        jLabel10.setText("Last");

        jLabel9.setText("First");

        addNewCustomerButton.setText("Add Customer");
        addNewCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewCustomerButtonActionPerformed(evt);
            }
        });

        addNewEntertainerButton.setText("Add Entertainer");
        addNewEntertainerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewEntertainerButtonActionPerformed(evt);
            }
        });

        entertainerNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entertainerNameFieldActionPerformed(evt);
            }
        });

        jLabel23.setText("Entertainer");

        jLabel24.setText("Name");

        jLabel25.setText("Type");

        jLabel26.setText("Fee");

        EntNameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(EntNameTable);

        CusNameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(CusNameTable);

        jButton1.setText("Remove Customer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remove Entertainer");

        RemoveEntertainerCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Entertainer" }));

        RemoveCustomerCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Remove Customer" }));
        RemoveCustomerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveCustomerComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entertainerNameField)
                            .addComponent(entertainerTypeField)
                            .addComponent(entertainerFeeField)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(addNewEntertainerButton))
                                    .addComponent(jLabel23))
                                .addGap(0, 283, Short.MAX_VALUE)))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RemoveEntertainerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemoveCustomerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel28)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(31, 31, 31))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(30, 30, 30)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(s)
                            .addComponent(l, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(e)
                            .addComponent(city)
                            .addComponent(p)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(addNewCustomerButton)))
                                .addGap(0, 225, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(87, 87, 87))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addNewCustomerButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entertainerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entertainerTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entertainerFeeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addNewEntertainerButton)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(RemoveEntertainerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(RemoveCustomerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pane.addTab("Add/Remove_Customer/Entertainer", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel21.setText("Entertainer");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Event Type" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        OverallEntPopularityButton.setText("Overall Popularity");
        OverallEntPopularityButton.setActionCommand("");
        OverallEntPopularityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OverallEntPopularityButtonActionPerformed(evt);
            }
        });

        TotalEntCountButton.setText("Total Count");
        TotalEntCountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalEntCountButtonActionPerformed(evt);
            }
        });

        EntCountByDateButton.setText("Count by Date");
        EntCountByDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntCountByDateButtonActionPerformed(evt);
            }
        });

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Entertainer" }));

        EvtCountTotalButon.setText("Total Count ");
        EvtCountTotalButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtCountTotalButonActionPerformed(evt);
            }
        });

        ShowAllCustomers.setText("Show All Customers");
        ShowAllCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAllCustomersActionPerformed(evt);
            }
        });

        showAllEventButton.setText("Show All Events");

        evtCountByDateButton.setText("Count By Date");
        evtCountByDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evtCountByDateButtonActionPerformed(evt);
            }
        });

        evtPopularity.setText("Type Popularity");

        jLabel3.setText("Event Type:");

        EntMostPopularButton.setText("Most Popular");
        EntMostPopularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntMostPopularButtonActionPerformed(evt);
            }
        });

        CustomersByLoyalty.setText("Customers by Loyalty");
        CustomersByLoyalty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomersByLoyaltyActionPerformed(evt);
            }
        });

        jLabel20.setText("From Date:");

        jLabel19.setText("To Date");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select  Event" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel32.setText("Booked Events");

        CustomerInvoiceButton.setText("Show Customer Invoice");
        CustomerInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerInvoiceButtonActionPerformed(evt);
            }
        });

        ShowFinancesForPerion.setText("Show Finances for Period");
        ShowFinancesForPerion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowFinancesForPerionActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FinanceDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addContainerGap())
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(FinanceDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel32)
                                            .addComponent(jLabel21))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel11Layout.createSequentialGroup()
                                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(CustomerInvoiceButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ShowAllCustomers)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CustomersByLoyalty)
                                                .addGap(169, 169, 169))
                                            .addGroup(jPanel11Layout.createSequentialGroup()
                                                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TotalEntCountButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EntCountByDateButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(EntMostPopularButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(OverallEntPopularityButton)
                                                .addContainerGap(184, Short.MAX_VALUE))))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(showAllEventButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(EvtCountTotalButon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(evtCountByDateButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(evtPopularity)
                                        .addGap(184, 184, 184))))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(726, Short.MAX_VALUE))))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(ShowFinancesForPerion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FinanceDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FinanceDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ShowFinancesForPerion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(TotalEntCountButton)
                            .addComponent(EntCountByDateButton)
                            .addComponent(EntMostPopularButton)
                            .addComponent(OverallEntPopularityButton))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(showAllEventButton)
                            .addComponent(evtCountByDateButton)
                            .addComponent(EvtCountTotalButon)
                            .addComponent(evtPopularity))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustomersByLoyalty)
                            .addComponent(ShowAllCustomers)
                            .addComponent(jLabel32)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustomerInvoiceButton))
                        .addGap(24, 24, 24)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Pane.addTab("Customer and Finances", jPanel3);

        jLabel1.setText("Choose entertainer");

        jLabel4.setText("First");

        jLabel5.setText("Last");

        fNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameFieldActionPerformed(evt);
            }
        });

        chooseEntNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseEntNameComboActionPerformed(evt);
            }
        });

        jLabel6.setText("House Number");

        jLabel7.setText("Postcode");

        jLabel22.setText("Email");

        dateChooserPanel1.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                dateChooserPanel1OnSelectionChange(evt);
            }
        });

        jLabel29.setText("Event Name");

        CreateFromNew.setText("Create Event From New Customer");
        CreateFromNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateFromNewActionPerformed(evt);
            }
        });

        jLabel30.setText("City");

        jLabel31.setText("Event Type");

        jPanel6.setBackground(new java.awt.Color(204, 206, 231));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText(" Event Name");

        selectEventNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Event Name" }));
        selectEventNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectEventNameComboActionPerformed(evt);
            }
        });

        jLabel15.setText("Entertainer");

        SelectEntNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Entertainer Name" }));
        SelectEntNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectEntNameComboActionPerformed(evt);
            }
        });

        AddEntToEventButton.setBackground(new java.awt.Color(204, 255, 255));
        AddEntToEventButton.setText("Add Entertainer to Event");
        AddEntToEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEntToEventButtonActionPerformed(evt);
            }
        });

        CreateFromExisting.setText("Create Event From Existing Customer");
        CreateFromExisting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateFromExistingActionPerformed(evt);
            }
        });

        CustomerEmailCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerEmailComboActionPerformed(evt);
            }
        });

        CusNameAddTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(CusNameAddTable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectEventNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SelectEntNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddEntToEventButton)
                .addGap(28, 28, 28)
                .addComponent(CustomerEmailCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(CreateFromExisting)
                .addGap(261, 261, 261))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(selectEventNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(SelectEntNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddEntToEventButton)
                    .addComponent(CreateFromExisting)
                    .addComponent(CustomerEmailCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addGap(20, 20, 20)
                                .addComponent(chooseEntNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addGap(10, 10, 10)
                                        .addComponent(eventNameField))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addGap(18, 18, 18)
                                        .addComponent(cityField))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(fNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addGap(8, 8, 8))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel22)
                                                    .addGap(18, 18, 18)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(32, 32, 32)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lNameField)
                                            .addComponent(pCodeField)
                                            .addComponent(eMailField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(evTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(CreateFromNew)))
                        .addGap(18, 18, 18)
                        .addComponent(dateChooserPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(676, 676, 676)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(addField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eMailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel29)
                                .addComponent(eventNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel31)
                                .addComponent(evTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(chooseEntNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(CreateFromNew))
                    .addComponent(dateChooserPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pane.addTab("Create New Event", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Pane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void ShowFinancesForPerionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowFinancesForPerionActionPerformed
        // TODO add your handling code here:

        ca = FinanceDateFrom.getSelectedDate();
        ca2 = FinanceDateTo.getSelectedDate();
        java.util.Date g;
        java.util.Date g2;
        g = ca.getTime();
        g2 = ca2.getTime();
        java.sql.Date sd = new java.sql.Date(g.getTime());
        java.sql.Date sd2 = new java.sql.Date(g2.getTime());
        EventConnection evet = new EventConnection("coursework");
        evet.determineProfit(jTable2,jTable3, sd, sd2);
    }//GEN-LAST:event_ShowFinancesForPerionActionPerformed

    private void CustomerInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerInvoiceButtonActionPerformed
        EventConnection evconect = new EventConnection("coursework");
        String evttName = jComboBox5.getSelectedItem().toString();
        System.out.println(evttName);
        evconect.showCustomerInvoice(jTable2, evttName);
        evconect.closeConnection();
    }//GEN-LAST:event_CustomerInvoiceButtonActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void CustomersByLoyaltyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomersByLoyaltyActionPerformed
        // TODO add your handling code here:
        EventConnection bob = new EventConnection("coursework");
        bob.showCustomersByLoyalty(jTable2);
        bob.closeConnection();
    }//GEN-LAST:event_CustomersByLoyaltyActionPerformed

    private void EntMostPopularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntMostPopularButtonActionPerformed
        // TODO add your handling code here:
        caly = FinanceDateFrom.getSelectedDate();
        caly2 = FinanceDateTo.getSelectedDate();
        java.util.Date dy;
        java.util.Date dy2;
        dy = caly.getTime();
        dy2 = caly2.getTime();
        java.sql.Date syd = new java.sql.Date(dy.getTime());
        java.sql.Date syd2 = new java.sql.Date(dy2.getTime());
        EntertainerConnection sod = new EntertainerConnection("coursework");
        sod.showMostPopularEntertainer(jTable2, syd, syd2);
    }//GEN-LAST:event_EntMostPopularButtonActionPerformed

    private void evtCountByDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evtCountByDateButtonActionPerformed
        // TODO add your handling code here:
        String eveType = jComboBox6.getSelectedItem().toString();
        caly = FinanceDateFrom.getSelectedDate();
        caly2 = FinanceDateTo.getSelectedDate();
        java.util.Date dy;
        java.util.Date dy2;
        dy = caly.getTime();
        dy2 = caly2.getTime();
        java.sql.Date syd = new java.sql.Date(dy.getTime());
        java.sql.Date syd2 = new java.sql.Date(dy2.getTime());
        EventConnection eveccc = new EventConnection("coursework");
        eveccc.countEventTypesByDate(eveType, jTable2, syd, syd2);
    }//GEN-LAST:event_evtCountByDateButtonActionPerformed

    private void ShowAllCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAllCustomersActionPerformed
        // TODO add your handling code here:
        EventConnection blob = new EventConnection("coursework");
        blob.showAllCustomers(jTable2);
        blob.closeConnection();
    }//GEN-LAST:event_ShowAllCustomersActionPerformed

    private void EvtCountTotalButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtCountTotalButonActionPerformed
        // TODO add your handling code here:
        String eveType = jComboBox6.getSelectedItem().toString();

        EventConnection eveccc = new EventConnection("coursework");
        eveccc.countEventTypes(eveType, jTable2);
    }//GEN-LAST:event_EvtCountTotalButonActionPerformed

    private void EntCountByDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntCountByDateButtonActionPerformed
        // TODO add your handling code here:
        String enName = jComboBox7.getSelectedItem().toString();
        cal = FinanceDateFrom.getSelectedDate();
        cal2 = FinanceDateTo.getSelectedDate();
        java.util.Date d;
        java.util.Date d2;
        d = cal.getTime();
        d2 = cal2.getTime();
        java.sql.Date sd = new java.sql.Date(d.getTime());
        java.sql.Date sd2 = new java.sql.Date(d2.getTime());

        date = sd;
        EntertainerConnection ede = new EntertainerConnection("coursework");
        ede.countEngagementsByDate(enName, jTable2, sd, sd2);
    }//GEN-LAST:event_EntCountByDateButtonActionPerformed

    private void TotalEntCountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalEntCountButtonActionPerformed
        // TODO add your handling code here:
        String enName = jComboBox7.getSelectedItem().toString();
        cal = FinanceDateFrom.getSelectedDate();
        cal2 = FinanceDateTo.getSelectedDate();
        java.util.Date d;
        java.util.Date d2;
        d = cal.getTime();
        d2 = cal2.getTime();
        java.sql.Date sd = new java.sql.Date(d.getTime());
        java.sql.Date sd2 = new java.sql.Date(d2.getTime());

        date = sd;
        EntertainerConnection ede = new EntertainerConnection("coursework");
        ede.countEngagements(enName, jTable2, sd, sd2);
    }//GEN-LAST:event_TotalEntCountButtonActionPerformed

    private void OverallEntPopularityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OverallEntPopularityButtonActionPerformed
        // TODO add your handling code here:
        c = FinanceDateFrom.getSelectedDate();
        c2 = FinanceDateTo.getSelectedDate();
        java.util.Date d;
        java.util.Date d2;
        d = c.getTime();
        d2 = c2.getTime();
        java.sql.Date siid = new java.sql.Date(d.getTime());
        java.sql.Date siid2 = new java.sql.Date(d2.getTime());
        EntertainerConnection e = new EntertainerConnection("coursework");
        e.showPopularity(jTable2, siid, siid2);
        e.closeConnection();
    }//GEN-LAST:event_OverallEntPopularityButtonActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void AddEntToEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEntToEventButtonActionPerformed
        try {
            // TODO add your handling code here:
            String EnterName = SelectEntNameCombo.getSelectedItem().toString();
            String EvenName = selectEventNameCombo.getSelectedItem().toString();
            System.out.println(EnterName);

            EntertainerConnection ec = new EntertainerConnection("coursework");
            ec.addEntertainerToEvent(EvenName, EnterName);
            ec.closeConnection();
        } catch (SQLException ex) {
            Logger.getLogger(EngagementFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddEntToEventButtonActionPerformed

    private void SelectEntNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectEntNameComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectEntNameComboActionPerformed

    private void selectEventNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectEventNameComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectEventNameComboActionPerformed

    private void CustomerEmailComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerEmailComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerEmailComboActionPerformed

    private void CreateFromExistingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateFromExistingActionPerformed
        try {
            // TODO add your handling code here:
            String custEmail = CustomerEmailCombo.getSelectedItem().toString();
            String evtttType = evTypeField.getText();
            String evtttName = eventNameField.getText();
            String enttttName = chooseEntNameCombo.getSelectedItem().toString();
            java.util.Date d;

            cal = dateChooserPanel1.getSelectedDate();
            d = cal.getTime();
            java.sql.Date sd = new java.sql.Date(d.getTime());
            date = sd;
            EventConnection ec = new EventConnection("coursework");
            ResultSet rs = ec.getDatesOfEntertainerEngagement(enttttName, date);

            if (!rs.next()) {
                Event evl = new Event(evtttType, sd, evtttName);
                ec.addEventFromExistingCustomer(evl, enttttName, custEmail);
                ec.closeConnection();
            } else {
                JOptionPane.showMessageDialog(null, "Entertainer is Already Booked on This Date.\nPlease Choose Another Date");
            }
        } catch (SQLException ex) {
            Logger.getLogger(EngagementFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CreateFromExistingActionPerformed

    private void CreateFromNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateFromNewActionPerformed

        try {
            // TODO add your handling code here:

            String cFName = fNameField.getText();

            String cLName = lNameField.getText();
            String cusAdd = addField.getText();
            try{
                cusNum = Integer.parseInt(cusAdd);
           
            
            String cusCity = cityField.getText();
            String cuspCode = pCodeField.getText();
            String cusEmail = eMailField.getText();
            String evType = evTypeField.getText();

            String evName = eventNameField.getText();
            String entName = chooseEntNameCombo.getSelectedItem().toString();
            if(cFName.isEmpty()){JOptionPane.showMessageDialog(null,"Please Enter A Value for First Name");}
            else if(cLName.isEmpty()){JOptionPane.showMessageDialog(null,"Please Enter A Value for Last Name");}
            else if(cusAdd.isEmpty()){JOptionPane.showMessageDialog(null,"Please Enter A Value for Address");}
            else if(cusCity.isEmpty()){JOptionPane.showMessageDialog(null,"Please Enter A Value for City");}
            else if(cuspCode.isEmpty()){JOptionPane.showMessageDialog(null,"Please Enter A Value for Postcode");}
            else if(cusEmail.isEmpty()){JOptionPane.showMessageDialog(null,"Please Enter A Value for Email");}
            else if(evType.isEmpty()){JOptionPane.showMessageDialog(null,"Please Enter A Value for Event Type");}
            else if(evName.isEmpty()){JOptionPane.showMessageDialog(null,"Please Enter A Value for Event Name");}
            else if(entName.isEmpty()){JOptionPane.showMessageDialog(null,"Please Select an Entertainers Name from The List");}
            else{
                Customer cus = new Customer(cFName, cLName, cusEmail, cusCity, cuspCode, cusNum);

                java.util.Date d;

                cal = dateChooserPanel1.getSelectedDate();
                d = cal.getTime();
                java.sql.Date sd = new java.sql.Date(d.getTime());
                date = sd;
                Event ev = new Event(evType, date, evName);
                EventConnection evc = new EventConnection("coursework");
                ResultSet rs = evc.getDatesOfEntertainerEngagement(entName, date);

                if (!rs.next()) {
                    evc.addEvent(ev, cus, entName, evName);
                    evc.showCustomerWithAddresses(CusNameAddTable);
                    evc.showCustomerNames(CusNameTable);
                    JOptionPane.showMessageDialog(null, "You Have Successfully Added a New Event");
                    selectEventNameCombo.removeAllItems();
                    evc.getEventNames(selectEventNameCombo);
                    evc.closeConnection();
                } else {
                    JOptionPane.showMessageDialog(null, "Entertainer Already Booked on This Date\nPlease Choose Another Date");
                }}}
             catch (NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Please enter a number value for House Number");
           
            }
            } catch (SQLException ex) {
                Logger.getLogger(EngagementFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

    }//GEN-LAST:event_CreateFromNewActionPerformed

    private void dateChooserPanel1OnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dateChooserPanel1OnSelectionChange
        // TODO add your handling code here:

        java.util.Date d;

        cal = dateChooserPanel1.getSelectedDate();
        d = cal.getTime();
        java.sql.Date sd = new java.sql.Date(d.getTime());
        date = sd;
    }//GEN-LAST:event_dateChooserPanel1OnSelectionChange

    private void chooseEntNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseEntNameComboActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_chooseEntNameComboActionPerformed

    private void fNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameFieldActionPerformed

    private void RemoveCustomerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveCustomerComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveCustomerComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void entertainerNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entertainerNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entertainerNameFieldActionPerformed

    private void addNewEntertainerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewEntertainerButtonActionPerformed
        try {
            // TODO add your handling code here:
            String name = entertainerNameField.getText();
            EntertainerConnection eC = new EntertainerConnection("coursework");
            ResultSet rs = eC.checkEntertainerExist(name);
            entertainerNameField.setText(null);

            if (!rs.next()) {
                try {

                    String type = entertainerTypeField.getText();
                    entertainerTypeField.setText(null);
                    String f = entertainerFeeField.getText();
                    int fee = Integer.parseInt(f);
                    entertainerFeeField.setText(null);
                    Entertainer newEnt = new Entertainer(name, type, fee);

                    eC.addEntertainer(newEnt);
                    JOptionPane.showMessageDialog(null, "Success");
                    eC.showEntertainersNames(EntNameTable);
                    chooseEntNameCombo.removeAllItems();
                    eC.getAllnames(chooseEntNameCombo);

                } catch (SQLException ex) {
                    Logger.getLogger(EngagementFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Please Enter a Numeric Value for Fee" + e.toString());
                }
                eC.closeConnection();
            } else {
                JOptionPane.showMessageDialog(null, "Entertainer Already Exists in Database");
            }
        } catch (SQLException ex) {
            Logger.getLogger(EngagementFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addNewEntertainerButtonActionPerformed

    private void addNewCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewCustomerButtonActionPerformed
        // TODO add your handling code here:

        String cFName = f.getText();

        String cLName = l.getText();
        String cusAdd = s.getText();
        try{
            int cusNum = Integer.parseInt(cusAdd);}
        catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Please enter a number value for House Number");
        }
        String cusCity = city.getText();
        String cuspCode = p.getText();
        String cusEmail = e.getText();

        if(cFName.isEmpty()){JOptionPane.showMessageDialog(null,"Please Enter A Value for First Name");}
        else if(cLName.isEmpty()){JOptionPane.showMessageDialog(null,"Please Enter A Value for Last Name");}
        else if(cusAdd.isEmpty()){JOptionPane.showMessageDialog(null,"Please Enter A Value for Address");}
        else if(cusCity.isEmpty()){JOptionPane.showMessageDialog(null,"Please Enter A Value for City");}
        else if(cuspCode.isEmpty()){JOptionPane.showMessageDialog(null,"Please Enter A Value for Postcode");}
        else if(cusEmail.isEmpty()){JOptionPane.showMessageDialog(null,"Please Enter A Value for Email");}

        else{
            Customer cus = new Customer(cFName, cLName, cusEmail, cusCity, cuspCode, cusNum);

            EventConnection evco = new EventConnection("coursework");
            evco.addNewCustomerToDatabase(cus);
            evco.showAllCustomers(CusNameTable);
            evco.showCustomerWithAddresses(CusNameAddTable);

    }//GEN-LAST:event_addNewCustomerButtonActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EngagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EngagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EngagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EngagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EngagementFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEntToEventButton;
    private javax.swing.JButton CreateFromExisting;
    private javax.swing.JButton CreateFromNew;
    private javax.swing.JTable CusNameAddTable;
    private javax.swing.JTable CusNameTable;
    private javax.swing.JComboBox<String> CustomerEmailCombo;
    private javax.swing.JButton CustomerInvoiceButton;
    private javax.swing.JButton CustomersByLoyalty;
    private javax.swing.JButton EntCountByDateButton;
    private javax.swing.JButton EntMostPopularButton;
    private javax.swing.JTable EntNameTable;
    private javax.swing.JButton EvtCountTotalButon;
    private datechooser.beans.DateChooserPanel FinanceDateFrom;
    private datechooser.beans.DateChooserPanel FinanceDateTo;
    private javax.swing.JButton OverallEntPopularityButton;
    private javax.swing.JTabbedPane Pane;
    private javax.swing.JComboBox<String> RemoveCustomerCombo;
    private javax.swing.JComboBox<String> RemoveEntertainerCombo;
    private javax.swing.JComboBox<String> SelectEntNameCombo;
    private javax.swing.JButton ShowAllCustomers;
    private javax.swing.JButton ShowFinancesForPerion;
    private javax.swing.JButton TotalEntCountButton;
    private javax.swing.JTextField addField;
    private javax.swing.JButton addNewCustomerButton;
    private javax.swing.JButton addNewEntertainerButton;
    private javax.swing.JComboBox<String> chooseEntNameCombo;
    private javax.swing.JTextField city;
    private javax.swing.JTextField cityField;
    private datechooser.beans.DateChooserPanel dateChooserPanel1;
    private javax.swing.JTextField e;
    private javax.swing.JTextField eMailField;
    private javax.swing.JTextField entertainerFeeField;
    private javax.swing.JTextField entertainerNameField;
    private javax.swing.JTextField entertainerTypeField;
    private javax.swing.JTextField evTypeField;
    private javax.swing.JTextField eventNameField;
    private javax.swing.JButton evtCountByDateButton;
    private javax.swing.JButton evtPopularity;
    private javax.swing.JTextField f;
    private javax.swing.JTextField fNameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField l;
    private javax.swing.JTextField lNameField;
    private javax.swing.JTextField p;
    private javax.swing.JTextField pCodeField;
    private javax.swing.JTextField s;
    private javax.swing.JComboBox<String> selectEventNameCombo;
    private javax.swing.JButton showAllEventButton;
    // End of variables declaration//GEN-END:variables
}
