/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import components.Module;

/**
 *
 * @author ste
 */
public class ModuleFrame extends javax.swing.JFrame {

    /**
     * Creates new form ModuleFrame
     */
    private MainFrame mainFrame;
    private Module newModule;
    private String title;
    private String code;
    private String number;
   
    public ModuleFrame(MainFrame mFrame) {
        initComponents();
        mainFrame = mFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldModuleTitle = new javax.swing.JTextField();
        jTextFieldModuleCode = new javax.swing.JTextField();
        jTextFieldNumberOfStudents = new javax.swing.JTextField();
        jLabelModuleTitle = new javax.swing.JLabel();
        jLabelModuleCode = new javax.swing.JLabel();
        jLabelNumberOfStudents = new javax.swing.JLabel();
        jButtonAddModule = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelModuleTitle.setText("Module Title: ");

        jLabelModuleCode.setText("Module Code: ");

        jLabelNumberOfStudents.setText("Number of Students: ");

        jButtonAddModule.setText("Add Module");
        jButtonAddModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddModuleActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAddModule)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelModuleTitle)
                        .addComponent(jLabelModuleCode, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNumberOfStudents)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldModuleTitle)
                    .addComponent(jTextFieldModuleCode, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jTextFieldNumberOfStudents, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldModuleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelModuleTitle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldModuleCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelModuleCode))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumberOfStudents)
                    .addComponent(jTextFieldNumberOfStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonAddModule))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddModuleActionPerformed
        // TODO add your handling code here:
        title = jTextFieldModuleTitle.getText();
        code = jTextFieldModuleCode.getText();
        number = jTextFieldNumberOfStudents.getText();
        int num = Integer.parseInt(number);
        
        Module newModule = new Module(title, code, num);
        mainFrame.addModule(newModule);
      dispose();
      mainFrame.setVisible(true);

        
     
    }//GEN-LAST:event_jButtonAddModuleActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
       
        mainFrame.setVisible(true);
       
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
  /*  public static void main(String args[]) {
  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuleFrame().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddModule;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabelModuleCode;
    private javax.swing.JLabel jLabelModuleTitle;
    private javax.swing.JLabel jLabelNumberOfStudents;
    private javax.swing.JTextField jTextFieldModuleCode;
    private javax.swing.JTextField jTextFieldModuleTitle;
    private javax.swing.JTextField jTextFieldNumberOfStudents;
    // End of variables declaration//GEN-END:variables

public String getTitle()
{
    return title;
}
    
public String getCode()
{
    return code;
}
public String getNumber()
{
    return number;
}

}
